name: Test comment

on:
  pull_request:

jobs:
  dogfood-append-sha:
    name: Dogfood
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Upsert comment
        uses: ./
        with:
          identifier: upsert-append-test
          insert: |
            Hello! Here's all the commits that have been made to this branch
            <!-- UPDATE_TEMPLATE -->
            * ${{ github.sha }} (latest)
          update: |
            * ${{ github.sha }} (latest)
          remove-regex: "/\\(latest\\)/gi"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  dogfood-replace-sha:
    name: Dogfood (replace)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Upsert comment
        uses: ./
        with:
          identifier: upsert-replace-test
          insert: |
            Hello! Here's the most recent commit to this branch:
            * ${{ github.sha }} (latest)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
